### ISSUE TITLE
Turn off the full screen

### ISSUE THREAD

**Issue by dianitamm** [santypr/jQuery.sliderFS#1]
Was looking into your slider code and I really like it, the transitions are excellent. But I do not need it to be full screen, is there any way to use it and turn off this feature? I just need it to be part of a page but on its own space(div).
Thank you!

**Comment by santypr** [comment]
Hi dianitamm. The slider fits into its parent so, if you define a container with some specific dimensions, the slider will fit in it.
Maybe i have to include some properties more to configure more behaviors like this :)

Thanks for your question.
